In [18]:
import requests
import json
from pandas.io.json import json_normalize

In [6]:
response = requests.get('https://acs.leagueoflegends.com/v1/stats/game/TRLH3/1001380191/timeline?gameHash=43a46f49938bacca')
time_line_data = json.loads(response.text)

In [116]:

first_result = json_normalize(time_line_data['frames'][0]['participantFrames']['1'])
first_result['time'] = time_line_data['frames'][0]['timestamp']
for i in range(2,11):
    result2 = json_normalize(time_line_data['frames'][0]['participantFrames'][str(i)])
    first_result = first_result.append(result2,sort=True)
    
for i in range(1,len((time_line_data['frames']))):
    for j in range(1,11):
        result2 = json_normalize(time_line_data['frames'][i]['participantFrames'][str(j)])
        result2['time'] = time_line_data['frames'][i]['timestamp']
        first_result = first_result.append(result2,sort=True)

In [117]:
first_result

,currentGold,dominionScore,jungleMinionsKilled,level,minionsKilled,participantId,position.x,position.y,teamScore,time,totalGold,xp
0,475,0,0,1,0,1,561,581,0,0.0,475,0
0,475,0,0,1,0,2,561,361,0,NaN,475,0
0,475,0,0,1,0,3,351,293,0,NaN,475,0
0,475,0,0,1,0,4,222,471,0,NaN,475,0
0,515,0,0,1,0,5,311,649,0,NaN,515,0
0,475,0,0,1,0,6,14486,14511,0,NaN,475,0
0,475,0,0,1,0,7,14486,14291,0,NaN,475,0
0,475,0,0,1,0,8,14277,14223,0,NaN,475,0
0,475,0,0,1,0,9,14148,14401,0,NaN,475,0
0,515,0,0,1,0,10,14237,14579,0,NaN,515,0
0,130,0,0,1,0,1,4128,9440,0,60000.0,475,0
0,5,0,0,1,0,2,6341,9441,0,60000.0,475,0
0,5,0,0,1,0,3,6545,8815,0,60000.0,475,0
0,0,0,0,1,0,4,9964,2664,0,60000.0,475,0
0,10,0,0,1,0,5,10301,2916,0,60000.0,515,0
0,0,0,0,1,0,6,3642,10941,0,60000.0,475,0
0,5,0,0,1,0,7,7050,9973,0,60000.0,475,0
0,5,0,0,1,0,8,9310,5684,0,60000.0,475,0
0,0,0,0,1,0,9,4675,13643,0,60000.0,475,0
0,10,0,0,1,0,10,11382,4993,0,60000.0,515,0
0,202,0,0,1,0,1,3900,6618,0,120000.0,547,0
0,137,0,1,1,0,2,8328,2590,0,120000.0,607,225
0,82,0,0,1,1,3,7072,6845,0,120000.0,552,58
0,57,0,0,1,0,4,9400,2610,0,120000.0,532,0
0,72,0,0,1,0,5,9490,2455,0,120000.0,577,0
0,57,0,0,1,0,6,11221,6940,0,120000.0,532,0
0,62,0,0,1,0,7,11110,7008,0,120000.0,532,0
0,82,0,0,1,1,8,7810,7879,0,120000.0,552,58
0,57,0,0,1,0,9,1948,11784,0,120000.0,532,0
0,72,0,0,1,0,10,3786,11016,0,120000.0,577,0
...,...,...,...,...,...,...,...,...,...,...,...,...
0,1030,0,22,16,226,1,13719,7704,0,1680000.0,10403,14915
0,1030,0,85,13,8,2,6804,11412,0,1680000.0,9610,11097
0,895,0,37,17,276,3,7915,8716,0,1680000.0,11645,16640
0,900,0,24,15,255,4,4732,12286,0,1680000.0,11595,14030
0,68,0,1,11,42,5,6687,7233,0,1680000.0,6703,8523
0,187,0,8,15,216,6,9595,13457,0,1680000.0,8290,13126
0,209,0,57,11,28,7,8648,10091,0,1680000.0,6464,8478
0,1094,0,15,15,267,8,12372,10257,0,1680000.0,9590,13063
0,992,0,1,12,222,9,12021,10619,0,1680000.0,8235,9698
0,176,0,2,11,23,10,8736,10426,0,1680000.0,4757,8039
0,480,0,24,16,226,1,8678,7855,0,1740000.0,10603,15193
0,1145,0,85,13,8,2,6973,9366,0,1740000.0,9725,11193
0,1207,0,37,17,284,3,7986,8720,0,1740000.0,11957,17093
0,1302,0,24,15,268,4,7364,9003,0,1740000.0,11997,14483
0,202,0,1,12,42,5,8184,10356,0,1740000.0,6837,8603
0,601,0,8,15,229,6,9974,11006,0,1740000.0,8704,13717
0,342,0,57,12,29,7,9157,10001,0,1740000.0,6597,8769
0,302,0,15,15,284,8,10038,10624,0,1740000.0,10113,13491
0,118,0,1,13,224,9,9483,9912,0,1740000.0,8397,10165
0,316,0,2,12,23,10,9398,10031,0,1740000.0,4897,8732
0,1078,0,24,16,238,1,8628,12714,0,1800000.0,11201,16126
0,1334,0,85,14,9,2,7759,11906,0,1800000.0,9914,11759
0,1744,0,39,17,291,3,7282,12704,0,1800000.0,12494,17802
0,2301,0,25,16,268,4,8298,12396,0,1800000.0,12996,14896
0,582,0,1,12,42,5,7700,11287,0,1800000.0,7217,9318
0,724,0,9,15,229,6,7821,10401,0,1800000.0,8828,13813
0,563,0,58,12,30,7,8842,12918,0,1800000.0,6818,9259
0,695,0,15,15,296,8,7888,10412,0,1800000.0,10506,13736
0,250,0,1,13,225,9,8818,13327,0,1800000.0,8528,10410
0,475,0,2,12,23,10,7480,12418,0,1800000.0,5056,9039

In [118]:
first_event = json_normalize(time_line_data['frames'][0]['events'])
first_event['time']= time_line_data['frames'][0]['timestamp']
for i in range(1,len((time_line_data['frames']))):
    result2 = json_normalize(time_line_data['frames'][i]['events'])
    result2['time'] = time_line_data['frames'][i]['timestamp']
    first_event = first_event.append(result2,sort=True)

In [119]:
first_event.to_csv('event.csv')